server.port=5000
spring.datasource.url=jdbc:postgresql://morganmoney-db.c8ruog8q0fuc.us-east-1.rds.amazonaws.com:5432/postgres
spring.datasource.username=morganadmin
spring.datasource.password=MorganMoney123!
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
aws.region=us-east-1
